cwweb/cwweb/app/courses/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import include, url
# import xadmin
from . import views
from .views import OrdersView , SelectView

urlpatterns = [
    url(r'^submitorder/(?P<order_id>[0-9]+)$', OrdersView.as_view(), name='sumbitorder'),
    url(r'^selectorder/$', SelectView.as_view(), name='selectorder'),
    url(r'^order_edit/$', views.order_edit, name='order_edit_action'),
    url(r'^delorder/(?P<order_id>[0-9]+)$', views.DelOrder, name='delorder'),
]

cwweb/cwweb/urls.py
#from django.contrib import admin
from django.conf.urls import include,url
import xadmin
from . import settings


urlpatterns = [
    #url('admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^',include('cwweb.app.users.urls')),
    url(r'^courses/',include('cwweb.app.courses.urls',namespace='courses')),
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
]

cwweb/cwweb/app/courses/models.py
from __future__ import unicode_literals
from django.db import models
# from datetime import date
from datetime import datetime
# from django.utils.timezone import now



class Orders(models.Model):
    num = models.IntegerField(default=0,verbose_name=u'凭证号')
    company_simple = models.CharField(max_length=30,verbose_name=u'公司简称')
    company = models.CharField(max_length=50,verbose_name=u'公司名称')
    money = models.IntegerField(default=0,verbose_name=u'金额')
    money_type = models.CharField(max_length=3,default=u'人民币',verbose_name=u'币种')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    add_date = models.DateTimeField(default=datetime.today,verbose_name=u'添加日期')
    class Meta:
        verbose_name = u'财务凭证'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.company

cwweb/cwweb/app/courses/forms.py
# -*-coding:utf-8-*-
__author__ = 'yxin'
__date__ = '18-4-8 下午10:04'
__product__ = 'PyCharm'


from django.db import models



from django import forms
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget


# Bootstrap 3

class TimeWidget(forms.Form):
    # start_time = forms.DateTimeField(widget=DateTimeWidget(usel10n=True, bootstrap_version=3))
    # end_time = forms.DateTimeField(widget=DateTimeWidget(usel10n=True, bootstrap_version=3))
    start_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    end_date = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    # time = forms.TimeField(widget=TimeWidget(usel10n=True, bootstrap_version=3))


class OrderForm(forms.Form):
    num = forms.IntegerField(required=True)
    company_simple = forms.CharField(max_length=20, required=True)
    company = forms.CharField(max_length=50, required=True)
    money = forms.IntegerField(required=True)
    # money_type = forms.CharField(max_length=3,default=u'人民币',verbose_name=u'币种')
    # add_time = forms.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

cwweb/cwweb/app/courses/views.py
# -*- conding:utf-8 -*-

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic.base import View
from .models import Orders
from .forms import OrderForm,TimeWidget
from django.utils.decorators import method_decorator
from django.http.response import HttpResponse
import datetime
import time

# Create your views here.

@method_decorator(login_required, name='dispatch')
class OrdersView(View):
    def get(self, request, order_id):
        if str(order_id) == '0':
            return render(request, 'courses/Orders.html', {})
        order = Orders.objects.get(pk=order_id)
        return render(request, 'courses/Orders.html', {'order': order})
    def post(self,request):
        pass

@login_required
def order_edit(request):
    form = OrderForm(request.POST)
    if form.is_valid():
        order_id = request.POST.get('order_id_hidden', '0')
        num = request.POST.get('num', '0')
        company_simple = request.POST.get('company_simple', '')
        company = request.POST.get('company', '')
        money = request.POST.get('money', '0')
        if str(order_id) == '0':
            order = Orders.objects.create(num=num, company_simple=company_simple,
                                          company=company, money=money)
            order.save()
            return render(request, 'users/index.html',{'middle':'表单提交成功'})
        else:
            order = Orders.objects.get(pk=order_id)
            order.num = num
            order.company = company
            order.company_simple = company_simple
            order.money = money
            order.save()
            return render(request, 'users/index.html',{'middle':(order.company_simple,'已修改')})
    else:
        return render(request, 'users/index.html', {'middle': 'error'})

@method_decorator(login_required, name='dispatch')
class SelectView(View):
    def get(self,request):
        orders = Orders.objects.all()
        Sum = 0
        for i in orders:
            Sum += int(i.money)
        if request.GET.get('id', None):
            form = TimeWidget(instance=TimeWidget.objects.get(id=request.GET.get('id', None)))
        else:
            form = TimeWidget()
        return render(request, 'courses/orderperforman.html'
                      , {'orders': orders, 'sum': Sum})


    def post(self,request):

            start = request.POST.get('start_date','')
            # start = "2018/04/09"
            tmp = time.strptime(start, "%m/%d/%Y")
            y = tmp.tm_year
            m = tmp.tm_mon
            d = tmp.tm_mday
            start_time = datetime.datetime(int(y),int(m),int(d),0,0)
            end = request.POST.get('end_date','')
            # end = "2018/04/11"
            tmp = time.strptime(end, "%m/%d/%Y")
            y = tmp.tm_year
            m = tmp.tm_mon
            d = tmp.tm_mday
            end_time = datetime.datetime(int(y),int(m),int(d),0,0)
            orders = Orders.objects.filter(add_time__range=(start_time,end_time))
            Sum = 0
            for i in orders:
                Sum += int(i.money)
            return render(request,'courses/orderperforman.html',
                          {'orders': orders, 'sum': Sum,})




@login_required
def index(request):
    return render(request, 'courses/index.html')
@login_required
def DelOrder(request,order_id):
    order = Orders.objects.get(pk=order_id)
    order.delete()
    return render(request,'users/index.html',{'middle':'删除成功'})

cwweb/cwweb/app/courses/templates/courses/Orders.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/headers/favicon.ico' %}">

    <title>添加/编辑表单</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>

<body class="text-center">
<form class="form-signin" action="{% url 'courses:order_edit_action' %}" method="post">
    {% csrf_token %}
    {% if order %}
    <input type="hidden" name="order_id_hidden" value="{{ order.id }}">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>凭证号</label>
                <input type="text" name="num" class="form-control" id="inputNum" placeholder="凭证号" value="{{order.num}}">
            </div>
            <div class="form-group col-md-6">
                <label>公司简称</label>
                <input type="text" name="company_simple" class="form-control" id="inputSimple_company"
                       placeholder="公司简称" value="{{ order.company_simple }}">
            </div>
        </div>
        <div class="form-group">
            <label>公司名称</label>
            <input type="text" name="company" class="form-control" id="inputCompany" placeholder="公司名称" value="{{ order.company }}">
        </div>
        <div class="form-group">
            <label for="inputAddress2">金额</label>
            <input type="text" name="money" class="form-control" id="money" placeholder="金额" value="{{ order.money }}">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>币种</label>
                <input type="text" name="money_type" class="form-control" id="money_type" placeholder="人民币">
 </div>      
 </div>
    {% else %}
     <input type="hidden" name="order_id_hidden" value="{{ 0 }}">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>凭证号</label>
                <input type="text" name="num" class="form-control" id="inputNum" placeholder="凭证号">
            </div>
            <div class="form-group col-md-6">
                <label>公司简称</label>
                <input type="text" name="company_simple" class="form-control" id="inputSimple_company"
                       placeholder="公司简称">
            </div>
        </div>
        <div class="form-group">
            <label>公司名称</label>
            <input type="text" name="company" class="form-control" id="inputCompany" placeholder="公司名称">
        </div>
        <div class="form-group">
            <label for="inputAddress2">金额</label>
            <input type="text" name="money" class="form-control" id="money" placeholder="金额">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>币种</label>
                <input type="text" name="money_type" class="form-control" id="money_type" placeholder="人民币">
            </div>
        </div>
    <button type="submit" class="btn btn-primary">提交</button>
</form>
</body>
</html>

cwweb/cwweb/app/courses/templates/courses/orderperforman.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/headers/favicon.ico' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.9.1.js"></script>
    <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://jqueryui.com/resources/demos/style.css">

    <title>表单查询</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
{#    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">#}
</head>
<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="">欢迎使用</a>
{#    <input class="from-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">#}
{#    <ul class="navbar-nav px-3">#}
{#        <li class="nav-item text-nowrap">#}
{#            <a class="nav-link" href="#">Sign out</a>#}
{#        </li>#}
{#    </ul>#}
</nav>
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <span></span>

                        </a>
                    </li>
                    <li class="nav-item">
{#                        <a class="nav-link" href="/index/">#}
                            <a class="nav-link" href="/index/">
                                <span data-feather="home"></span>
                                首页
                                <span class="sr-only">(current)</span>
                            </a>
{#                        </a>#}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <span data-feather="users"></span>
                            {{ request.session.user }}
                        </a>
                    </li>
                    <a class="nav-link" href="/logout/">
                        <span data-feather="file"></span>
                        退出
                    </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Saved reports</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            表单1
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            表单2
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            表单4
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            表单5
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                        <form action="{% url 'courses:selectorder' %}" method="post">
                            {% csrf_token %}
                            <a>日期查询</a>
                            <a><input type="text" id="datepicker" name="start_date" placeholder="04/01/2018"></a>
                            <a><input type="text" id="datepicker1" name="end_date" placeholder="04/11/2018"></a>
                            <a><input type="submit" value="确定"></a>
                        </form>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead align="center">
                        <tr>
                            <th>凭证号</th>
                            <th>公司名称</th>
                            <th>公司简称</th>
                            <th>金额</th>
                            <th>币种</th>
                            <th>添加时间</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody align="center">
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.num }}</td>
                                <td>{{ order.company }}</td>
                                <td>{{ order.company_simple }}</td>
                                <td>{{ order.money }}</td>
                                <td>{{ order.money_type }}</td>
                                <td>{{ order.add_time }}</td>
                                <td align="center"><a href="{% url 'courses:sumbitorder' order.id %}
">编辑</a>|<a href="{% url 'courses:delorder' order.id %}">删除</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot bgcolor="#b0c4de">
                        <tr>
                            <td colspan="6" align="left">累计金额</td>
                            <td align="center">{{ sum }}</td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
{#<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>#}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/hidden.js' %}"></script>
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>
</body>
</html>